git apply .\oda.patch
git apply .\experimental.patch
git apply .\use_nodepath_for_esm.patch
git apply .\add_v8_options.patch
git apply .\fix_gen_node_def.patch
git apply .\libuv_win7support.patch
git apply .\fix_v8_windows_build.patch
git apply .\disable_v8_slow_dcheck.patch
git apply .\fix_deps_undici.patch
git apply .\fix_vcbuild.patch
git apply .\debugging_console_app.patch